# Generated by Django 3.2 on 2021-06-05 18:22

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=coupon.models.random_code, max_length=6),
        ),
    ]
