# Generated by Django 3.2 on 2021-05-24 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('instructor', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('tagline', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='files/thumbnails')),
                ('resource', models.FileField(upload_to='files/resource')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.category')),
            ],
        ),
    ]
