# Generated by Django 3.2 on 2021-05-28 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_auto_20210526_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_type', models.CharField(choices=[('T', 'TEXT'), ('H', 'HEADING'), ('V', 'VIDEO'), ('L', 'LINK')], max_length=2)),
                ('index', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.course')),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_chapters', to='chapter.chapter')),
            ],
        ),
    ]
