# Generated by Django 3.2 on 2021-05-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0005_alter_chapter_parent_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parent_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_chapters', to='chapter.chapter'),
        ),
    ]
