# Generated by Django 3.2 on 2021-05-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0007_headingchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parent_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_chapters', to='chapter.chapter'),
        ),
    ]
