# Generated by Django 3.2 on 2021-06-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0008_alter_chapter_parent_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headingchapter',
            old_name='lecture',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='linkchapter',
            old_name='lecture',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='textchapter',
            old_name='lecture',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='videochapter',
            old_name='lecture',
            new_name='chapter',
        ),
    ]
