# Generated by Django 3.2 on 2021-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0009_auto_20210601_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
