# Generated by Django 3.2 on 2021-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210602_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('S', 'SUCCESS'), ('F', 'FAIL'), ('I', 'INITIATED')], default='I', max_length=2),
        ),
    ]
