# Generated by Django 3.2 on 2021-06-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
